[package]
name = "solana_timestamp_program"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.16"
borsh = "0.10"
borsh-derive = "0.10"
thiserror = "1.0"

[lib]
crate-type = ["cdylib", "lib"]
